import { buyerRole } from './roles'
import { John, myUrl, topMenu, dashboard, paymentsAccountPage, link } from './fixtures'


fixture`Stripe`.page(myUrl)

test.page(myUrl+ '/sign-up')('Stripe test', async (t) => {
  await t.useRole(buyerRole)
  .click(topMenu.buttons.menuDropdown)
  .click(topMenu.buttons.dashboard)
  .click(dashboard.nav.bankAccount)
  .click(dashboard.bankAccount.connectWithStripe)
  .wait(1000)
  .click(paymentsAccountPage.countrySelect)
  .click(paymentsAccountPage.select.countryOption.withText(John.country))
  .click(paymentsAccountPage.radiobutton.typeOfEntity)
  .typeText(paymentsAccountPage.input.mobilePhone, John.mobilePhone, { paste: true })
  .typeText(paymentsAccountPage.input.email, John.email, { replace: true }, { paste: true })
  .click(paymentsAccountPage.button.next)
  .click(paymentsAccountPage.button.useTestCode)
  .typeText(paymentsAccountPage.input.firstName, John.name, { paste: true })
  .typeText(paymentsAccountPage.input.lastName, John.lastName, { paste: true })
  .typeText(paymentsAccountPage.input.dobMonth, John.birthMonth, { paste: true })
  .typeText(paymentsAccountPage.input.dobDay, John.birthDay, { paste: true })
  .typeText(paymentsAccountPage.input.dobYear, John.birthYear, { paste: true })
  .typeText(paymentsAccountPage.input.addressStreet, John.addressStreet, { paste: true })
  .typeText(paymentsAccountPage.input.addressCity, John.addressCity, { paste: true })
  .typeText(paymentsAccountPage.input.addressCode, John.addressCode, { paste: true })
  .click(paymentsAccountPage.stateSelect)
  .click(paymentsAccountPage.select.stateOption.withText(John.state))
  .typeText(paymentsAccountPage.input.ssn, John.ssn, { paste: true })
  .click(paymentsAccountPage.button.next)
  .click(paymentsAccountPage.button.selectIndustrySelect)
  .click(paymentsAccountPage.select.industryOption)
  .typeText(paymentsAccountPage.input.companyWebsite, John.site, { paste: true })
  .click(paymentsAccountPage.button.next)
  .click(paymentsAccountPage.button.useTestAccount)
  .click(paymentsAccountPage.button.done)
  .click(link.withText('Continue'))
  .click(link.withText('Stripe Account Dashboard'))
})
